Integrated board hardware
doudar/SmartSpin2k pull request #402
Opened 2022-11-17 16:03 UTC by doudar

This change introduces the newest PCB with a serial interface specifically designed for integration with Peloton bikes and will provide a path for DIY'ers to order a board and cable kit that doesn't require any soldering skills. It's "print", "plug" and "play"

2022-11-22 21:07 UTC, eMadman requested changes
TODO: 

- [x] hyperlinks in readme.md don't work - relative links aren't working in our favor.
- [x] Readme.md for the main /hardware folder - needs a folder directory and descriptions to direct users

2022-11-25 01:36 UTC, doudar commented on Hardware/README.md
> +# [SmartSpin2K Hardware]
This file looks great!

2022-11-26 01:11 UTC, doudar commented
If .\Hardware\Common Assets\Arm\CAD\Bowflex C7.f3d from integrated board hardware is different from the current develop, we will need to manually add it back in after preforming this merge. I saved a local copy.

2022-11-26 03:05 UTC, eMadman commented
> If .\Hardware\Common Assets\Arm\CAD\Bowflex C7.f3d from integrated board hardware is different from the current develop, we will need to manually add it back in after preforming this merge. I saved a local copy.

Version on Develop is the most recent

2023-01-11 21:06 UTC, eMadman commented
My todos are not yet done but can move into a new PR.

2023-01-11 21:06 UTC, eMadman approved these changes

2023-01-11 21:08 UTC, merged